
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: gdte_development


test:
  <<: *default
  database: gdte_test

staging:
  <<: *default
  database: gdte_staging
  username: deploy
  password: <%= ENV["DATABASE_PASSWORD" ] %>
  
production:
  <<: *default
  database: gdte_production
  username: deploy
  password: <%= ENV["DATABASE_PASSWORD" ] %>